DELETE FROM public.lesson;
ALTER SEQUENCE public.lesson_id_seq RESTART WITH 1;
INSERT INTO public.lesson(
	instructor_id, instrument_kind, lesson_type, minimum_number_of_students, maximum_number_of_students, enrolled_students_number, lesson_level)
VALUES 
	(13, 'Drums', 'group', 2,30, 16, 'intermediate'),
	(7, 'Saxophone', 'individual', 1, 1, 1, 'advanced'),
	(10, 'Saxophone', 'individual', 1, 1, 1, 'advanced'),
	(2, 'Trumpet', 'individual', 1, 1, 1, 'beginner'),
	(15, 'Saxophone', 'individual', 1, 1, 1, 'advanced'),
	(11, 'Violin', 'group', 2,30, 24, 'advanced'),
	(4, 'Drums', 'individual', 1, 1, 1, 'beginner'),
	(2, 'Piano', 'group', 2,30, 19, 'intermediate'),
	(1, 'Clarinet', 'individual', 1, 1, 1, 'advanced'),
	(12, 'Trumpet', 'individual', 1, 1, 1, 'beginner'),
	(5, 'Drums', 'individual', 1, 1, 1, 'intermediate'),
	(10, 'Drums', 'group', 2,30, 9, 'advanced'),
	(7, 'Piano', 'group', 2,30, 18, 'beginner'),
	(5, 'Trumpet', 'group', 2,30, 17, 'advanced'),
	(3, 'Drums', 'group', 2,30, 12, 'advanced'),
	(8, 'Violin', 'individual', 1, 1, 1, 'beginner'),
	(7, 'Saxophone', 'group', 2,30, 17, 'beginner'),
	(9, 'Violin', 'group', 2,30, 10, 'advanced'),
	(11, 'Trumpet', 'group', 2,30, 18, 'beginner'),
	(8, 'Saxophone', 'individual', 1, 1, 1, 'beginner'),
	(8, 'Trumpet', 'group', 2,30, 13, 'intermediate'),
	(14, 'Trumpet', 'group', 2,30, 17, 'intermediate'),
	(3, 'Saxophone', 'group', 2,30, 26, 'advanced'),
	(9, 'Piano', 'group', 2,30, 12, 'advanced'),
	(15, 'Drums', 'individual', 1, 1, 1, 'advanced'),
	(13, 'Trumpet', 'individual', 1, 1, 1, 'beginner'),
	(11, 'Drums', 'group', 2,30, 5, 'beginner'),
	(15, 'Saxophone', 'group', 2,30, 30, 'beginner'),
	(9, 'Violin', 'individual', 1, 1, 1, 'beginner'),
	(4, 'Clarinet', 'individual', 1, 1, 1, 'beginner'),
	(9, 'Piano', 'individual', 1, 1, 1, 'intermediate'),
	(9, 'Saxophone', 'individual', 1, 1, 1, 'advanced'),
	(12, 'Clarinet', 'group', 2,30, 22, 'beginner'),
	(4, 'Drums', 'group', 2,30, 19, 'advanced'),
	(2, 'Trumpet', 'group', 2,30, 8, 'advanced'),
	(10, 'Violin', 'group', 2,30, 6, 'advanced'),
	(13, 'Trumpet', 'individual', 1, 1, 1, 'beginner'),
	(9, 'Saxophone', 'group', 2,30, 11, 'intermediate'),
	(3, 'Violin', 'individual', 1, 1, 1, 'beginner'),
	(10, 'Trumpet', 'group', 2,30, 6, 'advanced');